# Generated by Django 5.0.3 on 2024-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
