# Generated by Django 5.0.3 on 2024-03-26 02:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_post_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Classroom",
        ),
    ]
